sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  # Add Rust binaries to path
  - export PATH="$HOME/.cargo/bin:$PATH"
  # Install rustfmt if it does not already exist
  - if [[ ! -x "$HOME/.cargo/bin/cargo-fmt" ]]; then cargo install rustfmt; fi
script:
  # Check formatting of sources
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
cache: cargo
