sudo: false
language: rust
rust:
  - '1.22.1' # base line for backwards compatibility
  - stable # to stay up to date
  - beta # because the Rust team appreciates it
  - nightly
stages:
  - formatting
  - test
jobs:
  include:
    # Check formatting
    - stage: formatting
      before_install: rustup component add rustfmt-preview
      script: cargo fmt -- --write-mode=diff
      rust: nightly
    - stage: test
      script:
        - cargo build --verbose
        - cargo test --verbose
      cache: cargo
