sudo: false
language: rust
matrix:
  # Early fail/finish build if jobs fail
  fast_finish: true
  include:
    - rust: '1.17.0' # base line for backwards compatibility
    - rust: stable # to stay up to date
    - rust: beta # because the Rust team appreciates it
    # On nightly rust build with clippy enabled for linting
    - rust: nightly
      env: FEATURES="--features clippy"
before_install:
  # Add Rust binaries to path
  - export PATH="$HOME/.cargo/bin:$PATH"
  # Install rustfmt if it does not already exist
  - cargo install --vers 0.9.0 rustfmt
script:
  # Check formatting of sources
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo bench --verbose $FEATURES; fi
cache: cargo
notifications:
  # Disable all email notifications; we have CCMenu
  email: false
